version: '3.9'

services:
  web:
    build: .
    ports:
      - 8008:8008
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - TOKEN_EXPIRE_TIME=${TOKEN_EXPIRE_TIME}
      - TEST_USER_EMAIL=${TEST_USER_EMAIL}
    depends_on:
      - postgres
    entrypoint: uvicorn backend.app:app --host 0.0.0.0 --port 8008
  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_data:
