version: '3.9'

services:
  web:
    network_mode: "none"
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn backend.app:app --host 0.0.0.0'
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - TOKEN_EXPIRE_TIME=${TOKEN_EXPIRE_TIME}
      - TEST_USER_EMAIL=${TEST_USER_EMAIL}
    depends_on:
      - db
  db:
    network_mode: "none"
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_data: