FROM python:3.9.6-slim

WORKDIR /app
COPY . .

RUN apt-get update
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# run tests
CMD ["pytest", "--html=report.html", "tests"]
