version: '3'

services:
  web:
    build: .
    ports:
      - 8008:8008
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - TOKEN_EXPIRE_TIME=${TOKEN_EXPIRE_TIME}
      - TEST_USER_EMAIL=${TEST_USER_EMAIL}
    depends_on:
      - postgres
  postgres:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
